config/routes.rb
# frozen_string_literal: true
require 'resque/server'

Rails.application.routes.draw do

  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  delete '/admin/events/:id(.:format)' => 'events#destroy', as: :destroy_event

  mount RootApi => '/'

  mount Resque::Server.new, at: '/resque'

  root 'home#index'
  get 'stats', to: 'stats#index'
  get 'about', to: 'about#index'
  get 'emails', to: 'emails#index'

  post :toggle, to: 'locales#toggle'
  post :journal, to: 'events#journal'
  post '/events/:event_id/items/new(.:format)' => 'items#create', as: :create_item

  resources :users
  resources :roles
  resources :items
  resources :events

  resources :events do
    resources :items
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include AASM

  after_save :count_events
  after_destroy :recount_events

  validates :name, presence: true
  validates :name, length: { maximum: 500, minimum: 2 }
  validates :content, presence: true
  validates :content, length: { maximum: 2000, minimum: 5 }

  belongs_to :user, counter_cache: true
  has_many :items, dependent: :destroy
  #has_many :comments, as: :commentable, dependent: :delete_all #:nullify
  has_many :comments, as: :commentable, dependent: :nullify
  # has_many :users, through: :commnets
  has_many :comentators, through: :comments, source: :user
  has_many_attached :files #strict_loading: true

  aasm column: 'state' do
    state :created, initial: true, display: I18n.t('state.created')
    state :running, display: I18n.t('state.running')
    state :pending, display: I18n.t('state.pending')
    state :finished, display: I18n.t('state.finished')

    event :start do
      transitions from: %i[created running pending], to: :running
    end

    event :pend do
      transitions from: %i[running pending created], to: :pending
    end

    event :complete do
      transitions from: %i[running finished], to: :finished
    end
  end

  private

  def count_events
    user = User.where(id: user_id)
    if state
      user.limit(1).update(events_ffd_count: user.pluck(:events_ffd_count).first + 1)
    else
      user.limit(1).update(events_unffd_count: user.pluck(:events_unffd_count).first + 1)
    end
  end

  def recount_events
    user = User.where(id: user_id)
    if state
      user.limit(1).update(events_ffd_count: user.pluck(:events_ffd_count).first - 1)
    else
      user.limit(1).update(events_unffd_count: user.pluck(:events_unffd_count).first - 1)
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# class EventsController
class EventsController < ApplicationController
  include Commentable

  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  @rows_count = 5

  def index
    default_cookies(@rows_count) unless cookies[:start_date] || cookies[:final_date]
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    @start_date = cookies[:start_date].to_time
    @final_date = cookies[:final_date].to_time
    @users = User.includes(:events)
    events = Event.includes(:user)
    @events = TimeInterval.new([@start_date, @final_date], policy_scope(events), :items)
                          .journal[:rows].page(params[:page]).per(cookies[:rows_count])
  end

  def default_cookies(rows_count)
    cookies.permanent[:start_date] = DateTime.now.beginning_of_day
    cookies.permanent[:final_date] = DateTime.now.end_of_day
    cookies.permanent[:rows_count] = rows_count
  end

  def update_cookies
    cookies.permanent[:start_date] = @start_date
    cookies.permanent[:final_date] = @final_date
  end

  # GET /events/1 or /events/1.json
  def show
    authorize @event
    @comments = @event.comments#&.root&.self_and_descendants&.order(:lft)
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  # GET /events/new
  def new
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  def journal
    render_interval_query(event_params[:rows_count], event_params[:start_date], event_params[:final_date])
  end

  # POST /events or /events.json
  def create
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    @event = policy_scope(Event).new(event_params.merge(user: User.find(current_user.id)))
    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    authorize @event
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    authorize @event
    @event.destroy
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    # @event = Event.find(params[:id])
    @event = Event.with_attached_files.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :user_name, :content, :user, :created_at, :start_date, :final_date,
                                  :rows_count, :state, :page, files: [])
  end

  def render_interval_query(rows_count, start_date, final_date)
    #cookies.permanent[:rows_count] = rows_count
    @rows_count = rows_count
    @users = User.includes(:events)
    events = Event.includes(:user)
    check_events_count(events, start_date, final_date)
  end

  def check_events_count(events, start_date, final_date)
    if policy_scope(events).count.zero?
      @events = policy_scope(events).page(params[:page]).per(@rows_count)
      @start_date = cookies[:start_date].to_time
      @final_date = cookies[:final_date].to_time
      flash[:notice] = 'У пользователя нет заданий!'
    else
      data = TimeInterval.new([start_date, final_date], policy_scope(events), :items).journal
      @events = data[:rows].page(params[:page]).per(@rows_count)
      @start_date = data[:start_date]
      @final_date = data[:final_date]
      cookies.permanent[:rows_count] = @rows_count
    end
    update_cookies
    render :index
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.slim
div id = 'new_event' class = 'mb-3' style ='border: 1px dashed #0d6efd;
                                            padding: 10px;'
  = form_for @event do |f|
    - if @event.errors.any?
      #error_explanation
        h2 = "#{pluralize(@event.errors.count, 'error')} prohibited this event from being saved:"
        ul
          - @event.errors.full_messages.each do |message|
            li = message

    .field
      = f.label 'Задание', class: 'form-label'
      = f.text_field :name, class: 'form-control form-control-sm'

    .field
      = f.label 'Содержимое', class: 'form-label'
      = f.text_area :content, class: 'form-control form-control-sm'
    .field
      = f.label 'Статус', class: 'form-label'
      = f.select :state, options_for_select(['created', 'running', 'pending', 'finished'], selected: @event.state)
    .field
      = f.label :files, class: 'form-label'
      = f.file_field :files, multiple: true, class: 'form-control'    
    .actions 
      = f.submit 'Сохранить', class: 'btn btn-primary mb', id:'save_new_event_btn'

app/views/events/_form_journal_panel.html.slim
div id = 'calendar_event' class = 'mb-3' style ='margin: 10px;'
  = form_for :event, url: url_for(controller: :events, action: :journal) do |f|
    table.table.table
      thead
        .field
          tr
            th.col-1.st = f.label 'start_date'
            th.col-1.st = f.label 'finish_date'
            th.col-1.mid = f.label'count', style:"display: block; text-align:center;"
            th.col-1.mid = f.label 'submit', style:"display: block; text-align:center;"
            th.col-2.mid = f.label 'set interval', style:"display: block; text-align:center;"
      tbody
        .field
          tr
            td.col-1.st = f.date_field :start_date, value: @start_date.strftime("%Y-%m-%d"), class: 'form-control form-control-sm start_date', id:'start_date'
            td.col-1.st = f.date_field :final_date, value: @final_date.strftime("%Y-%m-%d"), class: 'form-control form-control-sm'
            td.col-1.mid = f.select(:rows_count, [['5'], ['15'], ['20'], ['25'], ['30'], ['35'], ['40']], {disabled: '40', selected: cookies[:rows_count].to_i}, id:"select_rows_count")
            td.col-1.mid = f.submit t('label.submit'), class: 'btn btn-secondary mb', data: { disable_with: false }, id:'app_journal_btn'
            td.col-2.bg-light.bg-gradient.mid = f.label "#{l(@start_date.to_date)} - #{l(@final_date.to_date)}", class:"text-black-50", style:"display: block; text-align:center;"
            td.col-6

app/views/events/_table_events.html.slim
div id = 'table_view' class = 'mb-3' style ='margin: 10px;'
  table.table.table-striped.events-all style ='margin: 5px;'
    thead
      tr
        th N
        th Пользователь
        th Задание
        th = t('Images') 
        th Дата создания
        th Статус
        th Подзадания 
        th Действия
    tbody
      - @events.order(created_at: :asc).each_with_index do |event, index|
        tr
          td = (index + 1) + (cookies[:rows_count].to_i * @events.current_page) - cookies[:rows_count].to_i
          td = event.user.name
          td = link_to event.name, event
          - if event.files.attached?
            td
              table
                - event.files.each_with_index do |file, i|
                  tr
                    td = link_to truncate(file.blob.filename.to_s, length: 20), rails_blob_path(file, only_path: true)
          - else
            td = ''    
          td = event.created_at.strftime("%d-%m-%Y, %H:%M")
          td = "V" if event.state == 'finished'
          td = event.items.count
          td 
            = link_to t('label.edit'), edit_event_path(event)
            =< link_to t('label.destroy'), event, data: { confirm: 'Are you sure?' }, method: :delete

app/views/events/edit.html.slim
div class = 'main-container mb-3' style ='margin: 15px 15px 0 10px; padding: 0 0 0 15px;'
  div class = 'mb-3'
    h1 Редактирование задания

    == render 'form'
  div class = 'mb-3'
    = link_to 'Show', @event, class: 'btn btn-primary'
    = link_to 'Back', event_path(@event.id), class: 'btn btn-primary', style: 'margin: 5px'

app/views/events/index.html.slim
div class = 'main-container mb-3' style ='margin: 5px; padding: 5px; padding-bottom: 40px;'
  div style ='margin-left: 15px;'
    h1 =t('label.list_events')
    p =flash[:notice]
  div id = 'date' class = 'mb-3' style ='margin: 0 10px 0 15px;'
    = render 'form_journal_panel'
  / div id = 'date_view' class = 'mb-3' style ='margin-left: 15px;'
  /   b ="#{t('label.period')}: "
  /   b =l(@start_date)
  /   b  - 
  /   b =l(@final_date)
  div id = 'paginate' class = 'events-paginate mb-3' style ='margin-left: 15px;'
    = paginate @events
  - if @rows_count != cookies[:rows_count]
    - cache [current_user, :events_list, params[:page]] do 
      == render 'table_events', cached: true
  - else 
    == render 'table_events'    
  div id = 'date_view' class = 'mb-3' style ='margin-left: 15px;'
    = link_to t('label.create_new_event'), new_event_path, class: 'btn btn-primary'
  div id = 'paginate' class = 'events-paginate mb-1' style ='margin-left: 15px;'
    = paginate @events

app/views/events/new.html.slim
div class = 'mb-3' style ='margin-left: 15px;'
  div class = 'mb-3' style ='margin-left: 10px;'
    h1 Новое задание

  == render 'form'

  div class = 'mb-3' style ='margin-left: 15px;'
    = link_to 'Back', events_path, class: 'btn btn-primary'

app/views/events/show.html.slim
/- cache @event do
div class = 'mb-3' style ='margin-left: 15px;'
  div class = 'mb-3 event' style ='margin-left: 10px;'
    p#notice = notice
    p
      strong ="#{t('activerecord.attributes.event.name')}: "
      br
      =< link_to @event.name, edit_event_path(@event)
      br
      br
      strong ="#{t('activerecord.attributes.event.content')}: "
      br
      =< link_to @event.content, edit_event_path(@event)
    - if @event.files.attached?
      table
        th = "N" 
        th = t('Images') 
        - @event.files.each_with_index do |file, i|
          - cache [file, i] do
            tr 
              td = i + 1
              td = link_to file.blob.filename, rails_blob_path(file, only_path: true)
    p 
      strong ="#{t('activerecord.attributes.event.done')}: "
      =< @event.state == 'finished' ? t('activerecord.attributes.event.finished') : t('activerecord.attributes.event.not_finished')
  div class = 'container' style ='padding: 15px;' 
    strong = t('activerecord.models.items')
    br
    = notice
    table.table.table-striped.table-items
      - @event.items.order(created_at: :desc).each_with_index do |item, i|
        - cache [item, i] do
          tr
            td = link_to "#{i + 1}", edit_event_item_path(item, { event_id: @event.id } )
            td = link_to item.name, edit_event_item_path(item, { event_id: @event.id } )
  div class = 'mb-3'
          
    = link_to t('label.back'), events_path, class: 'btn btn-primary'

    =< link_to t('label.new_item'), new_event_item_path(@event.id), class: 'btn btn-primary'