config/routes.rb
# frozen_string_literal: true
require 'resque/server'

Rails.application.routes.draw do

  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  delete '/admin/events/:id(.:format)' => 'events#destroy', as: :destroy_event

  mount RootApi => '/'

  mount Resque::Server.new, at: '/resque'

  root 'home#index'
  get 'stats', to: 'stats#index'
  get 'about', to: 'about#index'
  get 'emails', to: 'emails#index'

  post :toggle, to: 'locales#toggle'
  post :journal, to: 'events#journal'
  post '/events/:event_id/items/new(.:format)' => 'items#create', as: :create_item

  resources :users
  resources :roles
  resources :items
  resources :events

  resources :events do
    resources :items
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  after_save :count_items
  after_destroy :recount_items

  validates :name, presence: true
  validates :name, length: { maximum: 2000, minimum: 5 }

  belongs_to :event, touch: true, dependent: :destroy
  #has_one :has_user, through: :event#, source: :user, dependent: :destroy
  has_one :has_user, through: :event, source: :user

  private

  def count_items
    user = User.where(id: Event.where(id: event_id).pluck(:user_id).first)
    if done
      user.limit(1).update(items_ffd_count: user.pluck(:items_ffd_count).first + 1)
    else
      user.limit(1).update(items_unffd_count: user.pluck(:items_unffd_count).first + 1)
    end
  end

  def recount_items
    user = User.where(id: Event.where(id: event_id).pluck(:user_id).first)
    if done
      user.limit(1).update(items_ffd_count: user.pluck(:items_ffd_count).first - 1)
    else
      user.limit(1).update(items_unffd_count: user.pluck(:items_unffd_count).first - 1)
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  # GET /event/items or /event/items.json
  def index
    
    # @event_items = Item.where(event_id: Event.include(:items).pluck(:id))
    #@event = session[:event_id] ?  Event.find(session[:event_id]) : Event.find(params[:event_id])
    #@item = session[:id] ? Item.find(session[:id]) : Item.find(params[:id])
  
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    # @items = Item.where("event_id = #{params[:event_id]}")
  end

  # GET /event/items/1 or /event/items/1.json
  def show
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  # GET /event/items/new
  def new
    session[:event_id] = params[:event_id]
    @item = Item.new(event_id: session[:event_id])
    #@event = Event.find(params[:event_id])
    #@item = @event.items.create(event_id: @event.id)
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  # GET /event/items/1/edit
  def edit
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    @event = Event.find(params[:event_id])
  end

  # POST /event/items or /event/items.json
  def create
    @item = Item.new(item_params.merge(event_id: session[:event_id]))
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    #binding.pry
    respond_to do |format|
      if @item.save
        format.html { redirect_to event_path(@item.event_id), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        session[:event_id] = nil
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event/items/1 or /event/items/1.json
  def update
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to event_path(@item.event_id), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event/items/1 or /event/items/1.json
  def destroy
    @item.destroy
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
    respond_to do |format|
      format.html { redirect_to event_path(@item.event_id), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
      session[:event_id] = nil
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
   @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :done, :event_id, :id)
  end
end

app/views/items/_error_messages.html.slim
- if resource && resource.errors.any?
  .error-block#error_explanation
  /h2
    = I18n.t(count: resource.errors.count, resource: resource.class.model_name.human.downcase)
  ul
    - resource.errors.full_messages.each do |message|
      li.error_message_item
        = message

app/views/items/_form.html.slim
div id = 'table_items' class = 'mb-3' style ='margin: 10px;'
  /= link_to @event.name, :back
  = form_for @item do |f|
    table.table.table-striped class ='table table-striped' style ='margin: 5px;'
      thead
        tr
          th =t('№')
          th =t('activerecord.attributes.item.name')
          th =t('activerecord.attributes.item.done')
          th =t('activerecord.attributes.item.finished_at')
          th =t('label.actions')
      tbody
        .field
          f.tr
            td = 1
            td = f.text_area :name, class: 'form-control form-control-sm'
            td = f.check_box :done, {checked: @item.done}
            td = @item.finished_at ? item.finished_at.strftime("%d-%m-%Y, %H:%M") : t('activerecord.attributes.event.no_finished')
            td 
              = f.submit t('label.update'), data: { confirm: t('messages.questions.are_you_sure?') }, class: 'btn btn-dark', style: 'margin: 5px'
              = link_to t('label.destroy'), @item, data: { confirm: t('messages.questions.are_you_sure?') }, method: :delete, class: 'btn btn-dark', style: 'margin: 5px'
  div class = 'mb-3' style ='margin-left: 15px;'
    = link_to 'Back', event_path(@item.event_id), class: 'btn btn-primary'

app/views/items/edit.html.slim
h1 = t('activerecord.attributes.item.editing_item')
/div class = "container mb-3" style = "width: fit-content;"
== render 'form'

app/views/items/index.html.slim
h1 =t('activerecord.attributes.event.list_items')
p = t('activerecord.attributes.event.name')
= @event.name

== render 'form'

/= link_to 'New Item', new_item_path

app/views/items/new.html.slim
div class = 'mb-3' style ='margin-left: 15px;'
  div class = 'mb-3' style ='margin-left: 10px;'
    h1 Новое подзадание
    = "#{t('label.main_event')}: #{Event.find(@item.event_id).name}"
div id = 'table_items' class = 'mb-3' style ='margin: 10px;'
  /= link_to @event.name, :back
  br
  = render 'error_messages', resource: @item
  = form_for @item, url: create_item_path  do |f|
    /= f.hidden_field :event_id
    table.table.table-striped style ='margin: 5px;'
      thead
        tr
          th =t('№')
          th =t('activerecord.attributes.item.name')
          th =t('activerecord.attributes.item.done')
          th =t('activerecord.attributes.item.finished_at')
          th =t('label.save')
      tbody
        .field
          f.tr
            td = 1
            td = f.text_area :name, class: 'form-control form-control-sm'
            td = f.check_box :done, {checked: @item.done}
            td = @item.finished_at ? item.finished_at.strftime("%d-%m-%Y, %H:%M") : t('activerecord.attributes.event.no_finished')
            td = f.submit t('label.save'), data: { confirm: t('messages.questions.are_you_sure?') }, class: 'btn btn-dark', style: 'margin: 5px'   

  div class = 'mb-3' style ='margin-left: 15px;'
    = link_to 'Back', events_path, class: 'btn btn-primary'

app/views/items/show.html.slim
p#notice = notice

== render 'form'
/=> link_to 'Edit', edit_event_item_path(@item)
/ '|
/=< link_to 'Back', items_path